name: flux_store
description: "E-Commerce app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  cached_network_image: ^3.4.0
  connectivity_plus: ^5.0.2
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_html: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_native_splash: ^2.4.4
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^14.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  lottie: ^3.3.1
  modal_progress_hud_nsn: ^0.5.1
  number_display: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  svg_flutter: ^0.0.1
  translator: ^1.0.3+1
  url_launcher: ^6.3.1

  # Firebase & Notifications
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  intl_utils: ^2.8.8
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2


flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/banners/home_banner/
    - assets/images/lottie/
    - assets/images/on_boarding/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/icon.png"
flutter_intl:
  enabled: true
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helpers/
  filename: app_assets.dart
  field_prefix: null
